name: Publish new version upon tag commit
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '21'
            cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set version from tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build -Pversion=${VERSION:-${{ github.event.inputs.tag }}}

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: ${{ github.event.inputs.tag }}
            prerelease: ${{ contains(github.event.inputs.tag, '-') }}
            title: Release ${{ github.event.inputs.tag }}
            files: .gradle/build/*.jar
            body: |
              Release ${{ github.event.inputs.tag }}
              - [Changelog](../.github/Changelog.md)